### ISSUE TITLE
task make test function of add function.py

### ISSUE THREAD

**Issue by 7oda-dev** [7oda-dev/task6_csci313#2]
please , abderhman make test of add function.py 
include all cases 

1.  two numbers are positives
2. first number negative and second positive
3. first number positive and second is negative
4.  two numbers are nehative 
5.  one of numbers is string 
6.  two numbers is string
7.  one number is none and second number is none

**Comment by AbdelRahmanRahal** [comment]
Hi, Mahmoud.

I finished the unit testing for the `add()` function like required, and I also added the zero addition cases.

Check `unit_test_add.py` on the main branch.

Thanks.

**Comment by 7oda-dev** [comment]
[heart]         Mahmoud Mohamed Abdgelil reacted to your message:
________________________________

**Comment by 7oda-dev** [comment]
thanks, Abderhman (abo warda)

**Comment by 7oda-dev** [comment]
[heart]         Mahmoud Mohamed Abdgelil reacted to your message:
________________________________
